document.write("<table width=\"805\" border=\"0\" height=\"184\">");
document.write("<tbody>");
document.write("<tr>");
document.write("<td valign=\"top\"><br>");
document.write("<\/td>");
document.write("<td valign=\"top\"><br>");
document.write("<\/td>");
document.write("<\/tr>");
document.write("<tr>");
document.write("<td> <img src=\"imgs\/pr.jpg\" alt=\"Peter Richtarik\"");
document.write("width=\"161\" height=\"200\"> <\/td>");
document.write("<td>");
document.write("<h1>Peter Richtárik <\/h1>");
document.write("<h2>Associate Professor of Computer Science<\/h2>");
document.write("<h2><a href=\"https:\/\/kaust.edu.sa\/en\">KAUST<\/a><\/h2>");
document.write("<br>");
document.write("Address: Al Khawarizmi Building 1, Office 2221, Thuwal 23955-6900, Saudi Arabia <br>");
document.write("E-mail: peter.richtarik@kaust.edu.sa<br>");
document.write("<br>");
document.write("&nbsp;&nbsp;&nbsp;&nbsp; ");
document.write("<a href=\"https:\/\/scholar.google.com\/citations?user=pGh242UAAAAJ&amp;hl=en\"><img src=\"imgs\/scholar.png\" alt=\"Google Scholar\" width=\"25\" border=\"0\" height=\"25\"> <\/a> &nbsp;");
document.write("<a href=\"https:\/\/www.linkedin.com\/in\/richtarik\/\"> <img src=\"imgs\/linkedin.png\" alt=\"Linked In\" width=\"25\" border=\"0\" height=\"25\"><\/a><br>");
document.write("<\/td>");
document.write("<\/tr>");
document.write("<\/tbody>");
document.write("<\/table>");